pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/suhaib08/jenkins-project1.git'
            }
        }

        stage('Parallel Checks') {
            parallel {
                stage('Frontend Check') {
                    steps {
                        dir('project3-parallel') {
                            bat '"C:\\msys64\\ucrt64\\bin\\python.exe" frontend_check.py'
                        }
                    }
                }
                stage('Backend Check') {
                    steps {
                        dir('project3-parallel') {
                            bat '"C:\\msys64\\ucrt64\\bin\\python.exe" backend_check.py'
                        }
                    }
                }
            }
        }

        stage('Done') {
            steps {
                echo 'All checks completed.'
            }
        }
    }
}
